version: '3.8'
services:
  r2dbc_api:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:pool:postgresql://postgresdb:5432/people_db
    env_file:
      - .env
    container_name: reactive_api_service_container
    depends_on:
      - postgresdb
    networks:
      postgres_network:
    ports:
      - '9090:9090'
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2
  postgresdb:
    container_name: postgres_container_at_6432
    env_file:
      - .env
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_NAME
    ports:
      - '$POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT'
    networks:
      - postgres_network
    volumes:
      - ./init-scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgres
  es9200:
    container_name: es
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    image: elasticsearch:8.13.4
    ports:
      - 9200:9200
      - 9300:9300
networks:
  postgres_network:
volumes:
  postgres_data:
  es_data: