version: '3.8'
services:
  r2dbc_api:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:pool:postgresql://postgresdb:5432/people_db
    env_file:
      - .env
    container_name: reactive_api_service_container
    depends_on:
      - postgresdb
      - es9400
    networks:
      postgres_network:
      es_network:
    ports:
      - '9090:9090'
    stdin_open: true
    restart: on-failure
    tty: true
    volumes:
      - .m2:/root/.m2
  postgresdb:
    container_name: postgres_container_at_6432
    env_file:
      - .env
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_DB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_NAME
    ports:
      - "$POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT"
    expose:
      - "6432"
    networks:
      - postgres_network
    volumes:
      - ./init-scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - postgres_data:/var/lib/postgres
  es9400:
    container_name: es
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - SPRING_ELASTICSEARCH_URIS=es:9200
      - ELASTIC_PASSWORD=admin
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    image: elasticsearch:8.13.4
    ports:
      - "$ELASTIC_LOCAL_PORT_9400:$ELASTIC_DOCKER_PORT_9200"
      - "$ELASTIC_LOCAL_PORT_9500:$ELASTIC_DOCKER_PORT_9300"
    expose:
      - "9200"
    depends_on:
      - postgresdb
    networks:
      - es_network
networks:
  postgres_network:
  es_network:
volumes:
  postgres_data:
    driver: local
  es_data:
    driver: local