version: '3.8'
services:
  r2dbc_api:
    build: .
    env_file:
      - env_files/mysql.env
    container_name: reactive_api_service_container
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.r2dbc.url"  : "r2dbc:mysql://mysqldb4306:4306/people_db",
              "spring.r2dbc.username" : "docker",
              "spring.r2dbc.password" : "docker123"
            }'
    depends_on:
      - mysqldb4306
    networks:
      mysql_network:
    ports:
      - '9090:9090'
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2
  mysqldb4306:
    container_name: mysql_container_at_4306
    env_file:
      - env_files/mysql.env
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_USER: $MYSQLDB_USER
    ports:
      - '4306:3306'
    networks:
      - mysql_network
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  mysql_network:
volumes:
  mysql_data: